### ISSUE TITLE
mdb login does not ask for credentials

### ISSUE THREAD

**Issue by TomasKatz** [mdbootstrap/mdb-cli#11]
Just downloaded mdb-cli using npm.

When using the "mdb login" command nothing happens. 
Initially a browser popped up saying that an application was blocked, but the browser was accidentally  closed without resolving the issue. since then the command does absolutly nothing, e.g:

PS C:\Users\someuser\folder\project_root> mdb login
PS C:\Users\someuser\folder\project_root>

**Comment by catchmareck** [comment]
Since you have already submitted a ticket on our support forum here: https://mdbootstrap.com/support/other/mdb-cli1-1-20-mdb-login-does-not-ask-for-credentials/, I will close this issue and will assist you there, ok?
